import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    containerSos: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        paddingTop: 60,
        },
    container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    paddingTop: 80,
    },
    headerLogo: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: '8%',
    paddingBottom: 20,
    },
    headerLogin: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        paddingHorizontal: '8%',
        paddingTop: '10%',
        paddingBottom: 20,
        },
    backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'flex-start',
    },
    backIcon: {
    fontSize: 40,
    color: '#000',
    },
    containerActive: {
    backgroundColor: '#B73239',
    },
    sosTitle: {
    fontSize: 64,
    fontWeight: '800',
    color: '#B73239',
    letterSpacing: 8,
    marginBottom: 40,
    },
    sosTitleActive: {
    color: '#FFFFFF',
    },
    sosContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    },
    hexagonWrapper: {
    width: 300,
    height: 300,
    justifyContent: 'center',
    alignItems: 'center',
    },
    hexagonButton: {
    width: 300,
    height: 300,
    justifyContent: 'center',
    alignItems: 'center',
    },
    helpText: {
    marginTop: 40,
    fontSize: 18,
    fontWeight: '600',
    color: '#1A1A1A',
    },
    bottomSection: {
    width: '100%',
    paddingBottom: 40,
    alignItems: 'center',
    },
    statusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 30,
    },
    statusDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#4CAF50',
    marginRight: 10,
    },
    statusText: {
    fontSize: 16,
    color: '#333333',
    fontWeight: '500',
    },
    userCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 30,
    width: '85%',
    },
    userAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#8B9D6F',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    },
    userAvatarText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    },
    userName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1A1A1A',
    },
    sliderContainer: {
    width: '100%',
    paddingHorizontal: 30,
    paddingBottom: 60,
    },
    sliderTrack: {
    height: 70,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 35,
    justifyContent: 'center',
    paddingHorizontal: 8,
    position: 'relative',
    overflow: 'hidden',
    },
    sliderThumb: {
    position: 'absolute',
    left: 8,
    width: 54,
    height: 54,
    justifyContent: 'center',
    alignItems: 'center',
    },
    sliderCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#B73239',
    borderWidth: 3,
    borderColor: '#FFFFFF',
    },
    sliderText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1A1A1A',
    textAlign: 'center',
    marginLeft: 20,
    },

    scrollContainer: { flexGrow: 1, paddingHorizontal: 24, paddingTop: 30, paddingBottom: 40 },
    header: { alignItems: 'center', marginBottom: 40 },
    logo: { fontSize: 32, fontWeight: '700' },
    logoPlus: { color: '#2D5016', fontSize: 32, fontWeight: '700' },
    logoBosque: { color: '#2D5016', fontSize: 32, fontWeight: '700' },
    logoManu: { fontSize: 32, fontWeight: '700', color: '#000', marginTop: -8, paddingLeft: '30%', },
    greeting: { fontSize: 28, fontWeight: '700', color: '#2D5016', marginBottom: 40 },
    form: { marginBottom: 32 },
    inputContainer: { marginBottom: 24 },
    label: { fontSize: 16, fontWeight: '600', color: '#000', marginBottom: 8 },
    inputWrapper: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#E8E8E0', borderRadius: 12, paddingHorizontal: 16, height: 56 },
    input: { flex: 1, fontSize: 16, color: '#000' },
    iconButton: { padding: 8 },
    eyeIcon: { fontSize: 20 },
    forgotPassword: { fontSize: 14, color: '#666', textAlign: 'center', marginTop: 8, textDecorationLine: 'underline' },
    loginButton: { backgroundColor: '#2D5016', borderRadius: 12, height: 56, justifyContent: 'center', alignItems: 'center', marginBottom: 24 },
    loginButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '600' },
    footer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
    footerText: { fontSize: 14, color: '#666' },
    createAccountText: { fontSize: 14, color: '#2D5016', fontWeight: '600' },
    errorText: { color: 'red', textAlign: 'center', marginBottom: 16 },

    contentComplete: {
    flex: 1,
    paddingTop: 40,
    },
    scrollContainerComplete: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 40,
    },
    userNameComplete: {
    fontSize: 22,
    fontWeight: '700',
    color: '#000',
    textAlign: 'center',
    marginBottom: 8,
    },
    avatar: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: '#D8D8D0',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    },
    editIcon: {
    position: 'absolute',
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#F5F5F0',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#D8D8D0',
    },
    editIconText: {
    fontSize: 24,
    },
    sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#054324',
    marginBottom: 16,
    },
    allergyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    },
    removeButton: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    },
    removeIcon: {
    fontSize: 24,
    color: '#666',
    },
    allergyInput: {
    flex: 1,
    backgroundColor: '#E8E8E0',
    borderRadius: 8,
    height: 48,
    paddingHorizontal: 16,
    fontSize: 15,
    color: '#000',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    },
    clearButton: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    },
    clearIcon: {
    fontSize: 18,
    color: '#666',
    padding:8,
    },
    addAllergyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingLeft: 4,
    },
    addIcon: {
    fontSize: 24,
    color: '#2D5016',
    marginRight: 12,
    },
    addAllergyText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#2D5016',
    },
    loginButtonInitial: {
        width: '100%',
        backgroundColor: '#2D5016',
        borderRadius: 12,
        height: 56,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: {
          width: 0,
          height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 5,
      },
    continueButton: {
    backgroundColor: '#2D5016',
    borderRadius: 12,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#2D5016',
    shadowOffset: {
    width: 0,
    height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
    },
    loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    },
    headerProfile: {
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
    },
    scrollContainerModify: {
        paddingHorizontal: 24,
        paddingBottom: 40,
    },
    scrollContainerProfile: {
    paddingHorizontal: 24,
    paddingBottom: 40,
    alignItems: 'center',
    },
    avatarContainer: {
    marginBottom: 24,
    },
    avatarProfile: {
    width: 120,
    height: 120,
    borderRadius: 60,
    },
    userNameProfile: {
    fontSize: 25,
    fontWeight: '700',
    color: '#000',
    textAlign: 'center',
    marginBottom: 32,
    },
    infoContainer: {
    width: '100%',
    marginBottom: 40,
    },
    infoText: {
    fontSize: 18,
    fontWeight: '500',
    color: '#000',
    marginBottom: 12,
    },
    allergyItem: {
    fontSize: 18,
    fontWeight: '500',
    color: '#666',
    marginBottom: 6,
    },
    primaryButton: {
    width: '100%',
    backgroundColor: '#2D5016',
    borderRadius: 12,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    },
    dangerButton: {
    width: '100%',
    backgroundColor: '#A63C3C',
    borderRadius: 12,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    },
    outlineButton: {
    width: '100%',
    backgroundColor: 'transparent',
    borderRadius: 12,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#A63C3C',
    },
    outlineButtonText: {
    color: '#A63C3C',
    fontSize: 16,
    fontWeight: '600',
    },
    containerModify: {
    flex: 1,
    backgroundColor: '#F5F5F0',
    },
    headerModify: {
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
    backgroundColor: '#F5F5F0',
    },

    avatarContainerModify: {
    alignItems: 'center',
    marginBottom: 32,
    },

    editIconContainer: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F5F5F0',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#D8D8D0',
    },
    divider: {
    height: 1,
    backgroundColor: '#D0D0C8',
    marginVertical: 24,
    },
    passwordSectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
    marginBottom: 20,
    },
    backgroundImage: {
      flex: 1,
      width: '100%',
      height: '100%',
    },
    containerInitial: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
    },
    scrollContainerInitial: {
      flexGrow: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 32,
      paddingVertical: 60,
    },
    logoContainer: {
      alignItems: 'center',
      marginBottom: 120,
    },
    logoInitial: {
      fontSize: 60,
      fontWeight: '700',
    },
    logoPlusIntial: {
      color: '#FFFFFF',
      fontSize: 60,
      fontWeight: '700',
    },
    logoBosqueInitial: {
      color: '#FFFFFF',
      fontSize: 60,
      fontWeight: '700',
    },
    logoManuInitial: {
      fontSize: 60,
      fontWeight: '700',
      color: '#FFFFFF',
      marginTop: -8,
      paddingLeft: '30%',
    },
     checkbox: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#2D5016',
        marginRight: 5,
        marginTop: 2,
        justifyContent: 'center',
        alignItems: 'center',
      },
      checkboxFilled: {
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: '#2D5016',
      },
      termsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
        paddingHorizontal: 4,
      },
      termsText: {
        flex: 1,
        fontSize: 13,
        color: '#666',
        lineHeight: 20,
      },
      termsLink: {
        color: '#2D5016',
        fontWeight: '600',
        textDecorationLine: 'underline',
      },
    registerButton: {
      width: '100%',
      backgroundColor: 'rgba(255, 255, 255, 0.9)',
      borderRadius: 12,
      height: 56,
      justifyContent: 'center',
      alignItems: 'center',
    },
    registerButtonText: {
      color: '#2D5016',
      fontSize: 16,
      fontWeight: '600',
    },
});
